name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with unittests
      run: |
        python -m unittest tests.TestCalculator
    - name: Build executable
      run: |
        pip install pyinstaller
        pyinstaller --onefile main.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe
        path: dist/main.exe
